### ISSUE TITLE
Название пакета

### ISSUE THREAD

**Issue by sergant210** [bezumkin/modExtra#11]
А как сделать, чтобы название компонента не переводилось в нижний регистр? Для примера картинка. AjaxSnippet наверняка сделан на основе modExtra, но он с заглавными буквами.
![Картинка] (https://file.modx.pro/files/3/f/6/3f63ed4a84514fceb50858dfc4d0d9c9.png)

**Comment by bezumkin** [comment]
А это особенность установщика MODX - он запрашивает название из репозитория. Если пакет устанавливается локально, то название будет в нижнем регистре.
