### ISSUE TITLE
Ошибка Sendex в modx 2.4.3

### ISSUE THREAD

**Issue by skinysmn** [bezumkin/modExtra#16]
попытался пройти по статьям написания данного компонента, но после смены файла home.class.php получил ошибку 

> Fatal error: Class 'SendexMainController' not found in /public_html/Sendex/core/components/sendex/controllers/home.class.php on line 6

соответственно и финальная редакция компонента после установки выдает аналогичную ошибку.
неужели проблема в версии модх?

**Comment by bezumkin** [comment]
Нет, просто modExtra уже несколько раз переписан.

**Comment by skinysmn** [comment]
так и что делать? отчего приложение не работает? судя по ошибке не может найти расширяемый класс..

**Comment by bezumkin** [comment]
Без понятия

**Comment by skinysmn** [comment]
странно твой же компонент... )) а мысли в чем может быть дело есть? почему может теряться связь home.class.php и index.class.php?

**Comment by skinysmn** [comment]
причем сам modextra в стандарте работает..

**Comment by Nematjon** [comment]
У меня тодже ошибка
